Pages/AdminInterfejs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickFix.Models;

namespace QuickFix.Pages
{
    public class AdminInterfejsModel : PageModel
    {
        public ContextKlasa dbContext;

        public AdminInterfejsModel(ContextKlasa db) {
            dbContext = db;
        }

        [BindProperty]
        public Korisnik prijavljeniKorisnik { get; set; }

        [BindProperty]
        public List<Majstor> listaMajstora { get; set; }

        [BindProperty]
        public List<ZahtevServis> listaZahtevaZaServis { get; set; }

        [BindProperty]
        public List<ZahtevNovServis> listaZaRegistraciju { get; set; }

        [BindProperty]
        public Servis noviServis { get; set; }

        public void OnGet() {
            listaZaRegistraciju = dbContext.ZahtevZaNovServis.Where(x=>x.ZahtevNovServisStanje == "Na cekanju").ToList();
            listaMajstora = dbContext.Majstori.ToList();
            listaZahtevaZaServis = dbContext.ZahteviZaServise.Where(x=>x.StanjeZahteva == "Na cekanju").ToList();
        }

        public async Task<IActionResult> OnPostLogOutAsync() {
            Korisnik k = await dbContext.Korisnici.Where(x=>x.KorisnikPrijava == 1).FirstOrDefaultAsync();
            k.KorisnikPrijava = 0;
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/Prijava");
        }

        public async Task<IActionResult> OnPostRegistrujAsync(int id) {
            ZahtevNovServis zahtev = await dbContext.ZahtevZaNovServis.Where(x=>x.ZahtevNovServisId == id).FirstOrDefaultAsync();
            zahtev.ZahtevNovServisStanje = "Registrovan";
            
            noviServis.ServisIme = zahtev.ZahtevNovServisNaziv;
            noviServis.ServisLokacija = zahtev.ZahtevNovServisLokacija;
            noviServis.AdminEmail = zahtev.ZahtevNovServisAdminEmail;
            noviServis.AdminLozinka = zahtev.ZahtevNovServisAdminLozinka;
            noviServis.ServisAdminIme = zahtev.ZahtevNovServisAdminIme;
            noviServis.ServisAdminPrezime = zahtev.ZahtevNovServisAdminPrezime;
            noviServis.ServisAdminGod = zahtev.ZahtevNovServisAdminGod;
            noviServis.ServisAdminIskustvo = zahtev.ZahtevNovServisAdminIskustvo;
            noviServis.AdminPrijava = 0;

            dbContext.Servisi.Add(noviServis);
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminInterfejs");
        }

        public async Task<IActionResult> OnPostNeRegistrujAsync(int id) {
            ZahtevNovServis zahtev = await dbContext.ZahtevZaNovServis.Where(x=>x.ZahtevNovServisId == id).FirstOrDefaultAsync();
            zahtev.ZahtevNovServisStanje = "Odbijen";
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminInterfejs");
        }
    }
}

Pages/AdminServisaInterfejs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickFix.Models;

namespace QuickFix.Pages
{
    public class AdminServisaInterfejs : PageModel
    {
        public ContextKlasa dbContext;

        public AdminServisaInterfejs(ContextKlasa db) {
            dbContext = db;
        }

        [BindProperty]
        public Servis servis { get; set; }

        [BindProperty]
        public string noviNaziv { get; set; }

        [BindProperty]
        public string novaLokacija { get; set; }

        [BindProperty]
        public string novoIme { get; set; }

        [BindProperty]
        public string novoPrezime { get; set; }

        [BindProperty]
        public string noviBrGod { get; set; }

        [BindProperty]
        public string novoIskustvo { get; set; }

        [BindProperty]
        public string novaLozinka { get; set; }

        [BindProperty]
        public List<Majstor> listaMajstora { get; set; }

        [BindProperty]
        public List<ZahtevServis> listaZahtevaZaServis { get; set; }

        [BindProperty]
        public Majstor majstorZaUklanjanje { get; set; }

        public void OnGet() {
            servis = dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefault(); 
            listaMajstora = dbContext.Majstori.Where(x=>x.Servis == servis).ToList();
            listaZahtevaZaServis = dbContext.ZahteviZaServise.Where(x=>x.StanjeZahteva == "Na cekanju").Where(y=>y.Servis == servis).ToList();
        }

        public async Task<IActionResult> OnPostLogOutAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.ServisId == 1).FirstOrDefaultAsync();
            s.AdminPrijava = 0;
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/Prijava");
        }

        public async Task<IActionResult> OnPostPotvrdiAsync(int id) {
            ZahtevServis zahtev = await dbContext.ZahteviZaServise.Where(x=>x.ZahtevServisId == id).FirstOrDefaultAsync();
            zahtev.StanjeZahteva = "Potvrdjen";
            //Majstor podnosiocZahteva = await dbContext.Majstori.Where(x=>x.MajstorId == zahtev.Majstor.MajstorId).FirstOrDefaultAsync();
            //Servis trazeniServis = await dbContext.Servisi.Where(x=>x.ServisId == zahtev.Servis.ServisId).FirstOrDefaultAsync();
            Majstor podnosiocZahteva = await dbContext.Majstori.Where(y=>y.MajstorEmail == zahtev.EmailMajstora).FirstOrDefaultAsync();
            Servis trazeniServis = await dbContext.Servisi.Where(y=>y.ServisIme == zahtev.ImeServisa).FirstOrDefaultAsync();
            
            podnosiocZahteva.Servis = trazeniServis;
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostOdbiAsync(int id) {
            ZahtevServis zahtev = await dbContext.ZahteviZaServise.Where(x=>x.ZahtevServisId == id).FirstOrDefaultAsync();
            zahtev.StanjeZahteva = "Odbijen";
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniNazivServisaAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();

            if(noviNaziv != null)
            {
                if(noviNaziv.Length > 2)
                {
                    s.ServisIme = noviNaziv;
                }
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniLokacijuServisaAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();
            
            if(novaLokacija != null)
            {
                if(novaLokacija.Length > 2)
                {
                    s.ServisLokacija = novaLokacija;
                }
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniImeVlasnikaAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();
            if(novoIme != null)
            {
                if(novoIme.Length > 1)
                {
                    s.ServisAdminIme = novoIme;
                }
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniPrezimeVlasnikaAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();
            if(novoPrezime != null)
            {
                if(novoPrezime.Length > 1)
                {
                    s.ServisAdminPrezime = novoPrezime;
                }
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniBrGodVlasnikaAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();
            
            if(noviBrGod != null)
            {
                var isNumeric2 = int.TryParse(noviBrGod, out _);
                if(isNumeric2 == true)
                {
                    s.ServisAdminGod = noviBrGod;
                }
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniIskustvoVlasnikaAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();
            if(novoIskustvo != null)
            {
                s.ServisAdminIskustvo = novoIskustvo;
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }

        public async Task<IActionResult> OnPostIzmeniAdAsync() {
            Servis s = await dbContext.Servisi.Where(x=>x.AdminPrijava == 1).FirstOrDefaultAsync();
            if(novaLozinka != null)
            {
                if(novaLozinka.Length > 2)
                {
                    s.AdminLozinka = novaLozinka;
                }
                else
                {
                    return RedirectToPage("/AdminServisaInterfejs");
                }
            }

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/AdminServisaInterfejs");
        }
    }
}

Pages/KorisnickiInterfejs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickFix.Models;

namespace QuickFix.Pages
{
    public class KorisnickiInterfejsModel : PageModel
    {
        public ContextKlasa dbContext;

        public KorisnickiInterfejsModel(ContextKlasa db) {
            dbContext = db;
        }

        [BindProperty]
        public Korisnik prijavljeniKorisnik { get; set; }

        [BindProperty]
        public List<Majstor> listaMajstora { get; set; }

        [BindProperty]
        public List<Servis> listaServisa { get; set; }

        [BindProperty]
        public Zahtev noviZahtev { get; set; }

        [BindProperty]
        public List<Zahtev> listaZahteva { get; set; }

        [BindProperty]
        public Korisnik korisnikZaPodatke { get; set; }

        [BindProperty]
        public Majstor majstorZaPodatke { get; set; }

        [BindProperty]
        public int oceniMajstora { get; set; }

        [BindProperty]
        public string noviKomentar { get; set; }

        [BindProperty]
        public string IzabranServis { get; set; }

        [BindProperty]
        public string IzabranaUsluga { get; set; }

        [BindProperty]
        public string IzabranoIme { get; set; }

        [BindProperty]
        public int PostojiMajstorBezServisa { get; set; }

        [BindProperty(SupportsGet=true)]
        public Boolean ImaMajstora{get;set;}

        [BindProperty(SupportsGet=true)]
        public Boolean ImaUslugu{get;set;}

        public void OnGet() {
            PostojiMajstorBezServisa = 0;
            prijavljeniKorisnik = dbContext.Korisnici.Where(x=>x.KorisnikPrijava == 1).FirstOrDefault();
            listaMajstora = dbContext.Majstori.ToList();
            listaServisa = dbContext.Servisi.Include(x=> x.ListaMajstora).ToList();
            listaZahteva = dbContext.Zahtevi.Where(x=>x.Korisnik == prijavljeniKorisnik).ToList();

            foreach(Servis s in listaServisa)
            {
                foreach(Majstor m in s.ListaMajstora)
                {
                    m.Usluge=new List<Usluga>();
                    m.Usluge=dbContext.Usluge.Where(x=>x.Majstor==m).ToList();
                }
            }

           foreach(Majstor m in listaMajstora)
            {
                m.Usluge=new List<Usluga>();
                m.Usluge=dbContext.Usluge.Where(x=>x.Majstor==m).ToList();
            }
            
            foreach (var item in listaMajstora)
            {
                if (item.Servis == null)
                {
                    PostojiMajstorBezServisa = 1;
                }   
            }
        }

        public async Task<IActionResult> OnPostLogOutAsync() {
            Korisnik k = await dbContext.Korisnici.Where(x=>x.KorisnikPrijava == 1).FirstOrDefaultAsync();
            k.KorisnikPrijava = 0;
            await dbContext.SaveChangesAsync();
            return RedirectToPage("/Prijava");
        }

        public void OnPostPretrazi() {
            PostojiMajstorBezServisa = 0;
            prijavljeniKorisnik = dbContext.Korisnici.Where(x=>x.KorisnikPrijava == 1).FirstOrDefault();
            listaMajstora = dbContext.Majstori.ToList();
            listaServisa = dbContext.Servisi.Include(x=> x.ListaMajstora).ToList();
            listaZahteva = dbContext.Zahtevi.Where(x=>x.Korisnik == prijavljeniKorisnik).ToList();

           foreach(Servis s in listaServisa)
            {
                foreach(Majstor m in s.ListaMajstora)
                {
                    m.Usluge=new List<Usluga>();
                    m.Usluge=dbContext.Usluge.Where(x=>x.Majstor==m).ToList();
                }
            }

           foreach(Majstor m in listaMajstora)
            {
                m.Usluge=new List<Usluga>();
                m.Usluge=dbContext.Usluge.Where(x=>x.Majstor==m).ToList();
            }
            
            foreach (var item in listaMajstora)
            {
                if (item.Servis == null)
                {
                    PostojiMajstorBezServisa = 1;
                }   
            }
        }

        public async Task<IActionResult> OnPostKomentarisiAsync(int id,int majstor) {
            if(noviKomentar != null)
            {
                Korisnik k = await dbContext.Korisnici.Where(x=>x.KorisnikPrijava == 1).FirstOrDefaultAsync();
                Zahtev z = await dbContext.Zahtevi.FindAsync(id);
                Majstor m = await dbContext.Majstori.FindAsync(majstor);

                Komentar nk = new Komentar();
                nk.SadrzajKomentara = noviKomentar;
                nk.Korisnik = k;
                nk.Majstor = z.Majstor;
                nk.NazivKorisnika = k.KorisnikIme + " " + k.KorisnikPrezime;
                nk.MejlKorisnika = k.KorisnikEmail;

                dbContext.Komentari.Add(nk);
                await dbContext.SaveChangesAsync();
                return RedirectToPage("/KorisnickiInterfejs");
            }
            return RedirectToPage("/KorisnickiInterfejs");
        }

        public async Task<IActionResult> OnPostUkloniAsync(int id) {
            Zahtev zahtevZaBrisanje = await dbContext.Zahtevi.Where(x=>x.ZahtevId == id).FirstOrDefaultAsync();
            dbContext.Remove(zahtevZaBrisanje);
            await dbContext.SaveChangesAsync();

            await dbContext.SaveChangesAsync();
            return RedirectToPage("/KorisnickiInterfejs");
        }

        public async Task<IActionResult> OnPostOceniAsync(int id) {
            Zahtev odabranZahtev = await dbContext.Zahtevi.Where(x=>x.ZahtevId == id).FirstOrDefaultAsync();
            if(odabranZahtev.StanjeZahteva == "Popravljeno")
            {
                if (odabranZahtev.OcenjenZahtev != 1)
                {
                    Majstor odabranMajstor = await dbContext.Majstori.Where(y=>y.MajstorEmail == odabranZahtev.EmailMajstora).FirstOrDefaultAsync();
                    if (odabranMajstor.BrojOcena == 0)
                    {
                        odabranMajstor.BrojOcena = 1;
                        odabranZahtev.BrojOcenaMajstora = 1;
                        odabranMajstor.MajstorOcena = oceniMajstora;
                        odabranZahtev.OcenaMajstora = oceniMajstora;
                        odabranZahtev.OcenjenZahtev = 1;

                        await dbContext.SaveChangesAsync();
                        return RedirectToPage("/KorisnickiInterfejs");
                    }
                    else
                    {
                        odabranMajstor.BrojOcena++;
                        await dbContext.SaveChangesAsync();
                        odabranMajstor.MajstorOcena = (odabranMajstor.MajstorOcena + oceniMajstora) / 2;
                        odabranZahtev.BrojOcenaMajstora = odabranMajstor.BrojOcena;
                        odabranZahtev.OcenaMajstora = odabranMajstor.MajstorOcena;
                        odabranZahtev.OcenjenZahtev = 1;

                        await dbContext.SaveChangesAsync();
                        return RedirectToPage("/KorisnickiInterfejs");
                    }
                }
                else
                {
                    return RedirectToPage("/KorisnickiInterfejs");
                }                
            }
            else
            {
                return RedirectToPage("/KorisnickiInterfejs");
            }
        }
    }
}

Pages/AdminInterfejs.cshtml
@page
@model AdminInterfejsModel
@{
    ViewData["Title"] = "Admin Interfejs";
}

<form method="POST">
    <div class="adminDiv">
        <div class="adminDivLab">
            <h4>Zahtevi za Registraciju Servisa</h4>
        </div>
        <div class="adminDivTabela">
            <table class="table">
                <thead>
                    <tr>
                        <th>Podnosioc zahteva</th>
                        <th>Br.Godina</th>
                        <th>Iskustvo</th>
                        <th>Naziv servisa</th>
                        <th>Lokacija servisa</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var zahtev in Model.listaZaRegistraciju)
                    {
                        <tr>
                            <td>@zahtev.ZahtevNovServisAdminIme @zahtev.ZahtevNovServisAdminPrezime</td>
                            <td>@zahtev.ZahtevNovServisAdminGod</td>
                            <td>@zahtev.ZahtevNovServisAdminIskustvo</td>
                            <td>@zahtev.ZahtevNovServisNaziv</td>
                            <td>@zahtev.ZahtevNovServisLokacija</td>
                            <td><button type="submit" asp-page-handler="Registruj" asp-route-id="@zahtev.ZahtevNovServisId">Potvrdi</button></td>
                            <td><button type="submit" asp-page-handler="NeRegistruj" asp-route-id="@zahtev.ZahtevNovServisId">Odbi</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <button type="submit" class="odjavaDugme adminDivOdjava" asp-page-handler="LogOut">Log out</button>
    </div>
</form>

Pages/AdminServisaInterfejs.cshtml
@page
@model AdminServisaInterfejs
@{
    ViewData["Title"] = "Admin";
}

<div class="lider">
    <div class="serviskiDiv">
        <div class="serverskiLevi">
            <form method="GET">
                <h4>Podaci o Servisu</h4>

                <p><span class="labelaInf">Naziv servisa - </span>@Model.servis.ServisIme</p>
                <p><span class="labelaInf">Lokacija servisa - </span>@Model.servis.ServisLokacija</p>
            </form>

            <form method="POST">
                <div class="izmenaPodOSer">
                    <h2>Izmeni podatke o servisu</h2>

                    <div class="divcina">
                        <div class="labelcina">
                            Novi naziv servisa
                        </div>
                        <div class="divInputa">
                            <input type="text" asp-for="noviNaziv" id="nazivServisa">
                        </div>
                        <div>
                            <button class="dugmeSub" type="submit" asp-page-handler="IzmeniNazivServisa" onclick="IzmeniNazivServisa()">Izmeni naziv</button>
                        </div>
                    </div>

                    <div class="divcina">
                        <div class="labelcina">
                            Nova lokacija servisa
                        </div>
                        <div class="divInputa">
                            <input type="text" asp-for="novaLokacija" id="lokacijaServisa">
                        </div>
                        <div>
                            <button class="dugmeSub" type="submit" asp-page-handler="IzmeniLokacijuServisa" onclick="IzmeniLokacijuServisa()">Izmeni lokaciju</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="serverskiDesni">
            <div>
                <img src="~/Slike/service.jpg" alt="Service" class="servisnaSlika">
            </div>
        </div>
    </div>

    <div class="vlasnickiDiv">
        <div class="vlasnickiLevi">
            <form method="GET">
                <div class="tra">
                    <h2>Podaci o Vlasniku</h2>

                    <p><span class="labelaInf">Ime vlasnika - </span>@Model.servis.ServisAdminIme</p>
                    <p><span class="labelaInf">Prezime vlasnika - </span>@Model.servis.ServisAdminPrezime</p>
                    <p><span class="labelaInf">Broj godina - </span>@Model.servis.ServisAdminGod</p>
                    <p><span class="labelaInf">Iskustvo - </span>@Model.servis.ServisAdminIskustvo</p>
                </div>
            </form>
            <form method="POST">
                <div class="izmenaPodOVlasniku">
                    <h2>Izmeni podatke o vlasniku servisa</h2>

                    <div class="divcina">
                        <div class="labelcina">
                            Ime
                        </div>
                        <div class="divInputa">
                            <input type="text" asp-for="novoIme" id="imeVlasnika">
                        </div>
                        <div>
                            <button type="submit" asp-page-handler="IzmeniImeVlasnika" onclick="IzmeniImeVlasnika()">Izmeni</button>
                        </div>
                    </div>

                    <div class="divcina">
                        <div class="labelcina">
                            Prezime
                        </div>
                        <div class="divInputa">
                            <input type="text" asp-for="novoPrezime" id="prezimeVlasnika">
                        </div>
                        <div>
                            <button type="submit" asp-page-handler="IzmeniPrezimeVlasnika" onclick="IzmeniPrezimeVlasnika()">Izmeni</button>
                        </div>
                    </div>

                    <div class="divcina">
                        <div class="labelcina">
                            Broj godina
                        </div>
                        <div class="divInputa">
                            <input type="text" asp-for="noviBrGod" id="godineVlasnika">
                        </div>
                        <div>
                            <button type="submit" asp-page-handler="IzmeniBrGodVlasnika" >Izmeni</button>
                        </div>
                    </div>

                    <div class="divcina">
                        <div class="labelcina">
                            Iskustvo
                        </div>
                        <div class="divInputa">
                            <input type="text" asp-for="novoIskustvo" id="iskustvoVlasnika">
                        </div>
                        <div>
                            <button type="submit" asp-page-handler="IzmeniIskustvoVlasnika" onclick="IzmeniIskustvoVlasnika()">Izmeni</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="vlasnickiDesni">
            <div>
                <img src="~/Slike/korisnik.png" alt="Vlasnik" class="vlasnickaSlicica">
            </div>
        </div>
    </div>

    <div class="divAdm">
        <form method="POST">
            <div class="izmenaPodOAdministratoru">
                <h2>Izmeni podatke o Administratoru</h2>

                <div class="divcinaa">
                    <div class="labelcinab">
                        Nova lozinka
                    </div>
                    <div class="divInputa">
                        <input type="password"  id="myInput" asp-for="novaLozinka">
                        <input type="checkbox" onclick="pokazz()">Prikazi lozinku
                    </div>
                    <div>
                        <button type="submit" asp-page-handler="IzmeniAd" onclick="IzmeniPodatkeOAdministratoru()">Izmeni</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="zahtevi">
        <form method="POST">
            <div class="lefft">
                <h4>Pregled svih registrovanih majstora</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Ime</th>
                            <th>Prezime</th>
                            <th>Email</th>
                            <th>Ocena (Broj ocena)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var majstor in Model.listaMajstora)
                        {
                            <tr>
                                <th>@majstor.MajstorIme</th>
                                <th>@majstor.MajstorPrezime</th>
                                <th>@majstor.MajstorEmail</th>
                                <th>@majstor.MajstorOcena (@majstor.BrojOcena)</th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="lefft">
                <h4>Zahtevi za Servis</h4>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Ime Majstora</th>
                            <th>Prezime Majstora</th>
                            <th>Email Majstora</th>
                            <th>Ocena Majstora (Broj ocena)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var zahtev in Model.listaZahtevaZaServis)
                        {
                            <tr>
                                <td>@zahtev.ImeMajstora</td>
                                <td>@zahtev.PrezimeMajstora</td>
                                <td>@zahtev.EmailMajstora</td>
                                <td>@zahtev.OcenaMajstora (@zahtev.BrojOcenaMajstora)</td>
                                <td><button type="submit" asp-page-handler="Potvrdi" asp-route-id="@zahtev.ZahtevServisId">Potvrdi</button></td>
                                <td><button type="submit" asp-page-handler="Odbi" asp-route-id="@zahtev.ZahtevServisId">Odbi</button></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </form>
    </div>
    <form method="POST">
        <button type="submit" class="odjavaDugme dab" asp-page-handler="LogOut">Log out</button>
    </form>
</div>

<script>
    function pokazz() {
        var x = document.getElementById("myInput");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>

Pages/Majstor.cshtml
@page
@model MajstorModel
@{
    ViewData["Title"] = "Informacije Majstora";
}

<div class="majstorDiv">
    <form method="POST">
        <div class="majstorSlicica">
            <div>
                <img src="~/Slike/majstor.png" alt="Majstor" class="majstorPhoto">
            </div>
        </div>

        <div class="osnovneInfOMajstoru">
            <div class="osnovniPodaciOMaj">
                <h3>Osnovni podaci Majstora</h3>
                <p><span class="labelaInf">Ime i prezime - </span>@Model.odabraniMajstor.MajstorIme @Model.odabraniMajstor.MajstorPrezime</p>
                <p><span class="labelaInf">Email - </span>@Model.odabraniMajstor.MajstorEmail</p>
                <p>
                    <span class="labelaInf">Ocena (Broj ocena) - </span>@Model.odabraniMajstor.MajstorOcena (@Model.odabraniMajstor.BrojOcena)
                </p>
            </div>
        </div>

        <div class="tabelaInfMaj">
            <table class="table">
                <thead>
                    <tr>
                        <th>Naziv usluge</th>
                        <th>Cena</th>
                        <th>Zakazivanje</th>                                
                    </tr>
                </thead>
                <tbody>
                    @foreach (var usluga in Model.listaUsluga)
                    {
                        <tr>
                            <td>@usluga.NazivUsluge</td>
                            <td>@usluga.CenaUsluge</td>
                            <td><button type="submit" class="zakaziDugme" asp-route-idd="@usluga.UslugaId" asp-route-majstorId="@usluga.Majstor.MajstorId" asp-page-handler="Zakazi">Zakazi</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="komentarskiDiv">
            <div class="divZaKomentare">
                <h2>Komentari</h2>
                @foreach (var komentar in Model.listaKomentara)
                {
                    <div class="divKomentara">
                        <div class="podnosiocKomentara">
                            <p><span class="labelaInf">Komentarisao - </span>@komentar.NazivKorisnika (@komentar.MejlKorisnika)</p>
                        </div>
                        <div class="sadrzajKomentara">
                            <div class="komentarSadrzaj">
                                <p>@komentar.SadrzajKomentara</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </form>
</div>